name: Destroy Review App on Close
on:
  pull_request:
    types: [closed]

jobs:
  destroy-review-app:
    runs-on: ubuntu-latest

    steps:
      - uses: fastruby/manage-heroku-review-app@v1
        with:
          action: destroy
        env:
          HEROKU_API_TOKEN: ${{ secrets.HEROKU_API_TOKEN }}
          HEROKU_PIPELINE_ID: ${{ secrets.HEROKU_PIPELINE_ID }}